### ISSUE TITLE
Create a header/footer that links back to main website

### ISSUE THREAD

**Issue by locks** [glimmerjs/glimmer-playground#9]
Since we are linking from the main website to the playground, it would be nice to do the reverse and link the two websites closer.
The design is still up for grabs.

cc @nummi since you've already touched the project, you might want to tackle this one.

**Comment by nummi** [comment]
I'd be happy to take a stab at it. I already have a PR in the works to introduce a header. :-D

**Comment by nummi** [comment]
<img width="1380" alt="screen shot 2017-11-04 at 10 39 11 am" src="https://user-images.githubusercontent.com/3692/32407969-a9ed20f0-c14d-11e7-9b4d-2afdbc88c228.png">

**Comment by locks** [comment]
Boom :D
